openapi: 3.0.0
info:
  title: AI News Curation API - Newsletter Draft and Secure Sending
  version: 1.3.0

paths:
  /api/newsletters/{id}/items:
    get:
      summary: Get items for a specific newsletter draft
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of items sorted by display_order

  /api/newsletters/{id}/reorder:
    put:
      summary: Update the display order of items in a draft
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                item_orders:
                  type: array
                  items:
                    type: object
                    properties:
                      trend_item_id:
                        type: integer
                      display_order:
                        type: integer
      responses:
        '200':
          description: Order updated successfully

  /api/newsletters/{id}/send-test:
    post:
      summary: Send a test email to the administrator
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Test mail sent successfully

  /api/newsletters/confirm/{uuid}:
    get:
      summary: Confirm and trigger the full distribution
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Final distribution triggered successfully
        '409':
          description: Newsletter already sent or in progress
        '404':
          description: Invalid or expired confirmation link
